version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbotpass
      POSTGRES_DB: chatbotdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://chatbot:chatbotpass@db:5432/chatbotdb
      # Optionally set SECRET_KEY, etc.
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt

volumes:
  db_data:
