version: '3.8'
services:
  test-run:
    build: .
    depends_on:
      - db
    environment:
      TEST_DATABASE_URL: postgresql://chatbot:chatbotpass@db:5432/chatbotdb_test
      DATABASE_URL: postgresql://chatbot:chatbotpass@db:5432/chatbotdb
    command: ["/bin/sh", "-c", "sleep 5 && pytest --cov=app --cov-report=term-missing --cov-report=html tests/unit tests/integration --disable-warnings -q -ra"]
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt
      - ./tests:/app/tests
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbotpass
      POSTGRES_DB: chatbotdb
      # Also create the test database for integration tests
      POSTGRES_MULTIPLE_DATABASES: chatbotdb_test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      # Custom entrypoint to create multiple databases
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://chatbot:chatbotpass@db:5432/chatbotdb
      # Optionally set SECRET_KEY, etc.
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./app:/app/app
      - ./requirements.txt:/app/requirements.txt

volumes:
  db_data:
